# Constrain parameter values...
def pow2[n: Int]() -> Int where n >= 0: ...

# ...multiple parameters at once...
def subspan[start: Int, end: Int](self) -> Self where end > start: ...

# ...or gate a method on the element type's traits.
# The struct works for all T; sorting only where sortable:
def sort(self) where conforms_to(Self.T, Comparable): ...
